### ISSUE TITLE
error.php file can't be opened, breaks site on startup

### ISSUE THREAD

**Issue by erict-dev** [andromedus/191B#30]
![screen shot 2015-01-20 at 10 58 33 pm](https://cloud.githubusercontent.com/assets/4564093/5832304/fdd5d2da-a0f7-11e4-991c-2ea9e1f66375.png)

Looks like it's trying to open the /vagrant/app/errors.php file and failing. The error comes from the fact that I don't have this file in my app directory. I have the latest pull. I'm thinking it could possibly be an untracked change or a new file added that was accidentally forgotten to be added with the commit?

**Comment by hoshinoa** [comment]
Added app/errors.php as was advised! Thank you for the heads up and the suggestion, Eric!
